version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: 
          command: npm install -g contentful-cli
  test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: 
          command: npm install -g contentful-cli
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build        

