version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: 
          command:'npm install -r package.json' 
  test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: 
          command:'npm install -r package.json'
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build        

